import Link from "next/link";
import { FileCheck, Download, Beaker, ShieldCheck } from "lucide-react";
import { db } from "@/db";

export const metadata = {
  title: "Certificates of Analysis",
  description: "View COA documentation for our research peptide products.",
};

export default async function CoaPage() {
  const products = await db.product.findMany({
    where: { coaUrl: { not: null } },
    orderBy: { name: "asc" },
    select: { id: true, displayName: true, dosage: true, sku: true, coaUrl: true, categoryLabel: true },
  });

  return (
    <>
      <section className="py-14 border-b border-[var(--prg-border)] prg-page-hero-gradient">
        <div className="prg-container max-w-[820px]">
          <span className="prg-eyebrow">Quality Documentation</span>
          <h1 className="text-[clamp(32px,4vw,42px)] font-bold uppercase tracking-[2px] mb-3 mt-2" style={{ fontFamily: "var(--font-display)" }}>
            Certificates of Analysis
          </h1>
          <p className="text-[17px] text-[var(--prg-text-secondary)] leading-[1.7] max-w-[640px]">
            Every product lot is third-party tested. Download COA documents below to verify purity,
            identity, and quality specifications.
          </p>
        </div>
      </section>

      <section className="py-16">
        <div className="prg-container max-w-[820px]">
          <div className="p-5 bg-[var(--prg-bg-alt)] border-l-4 border-[var(--prg-accent)] rounded-r-[4px] mb-10">
            <h2 className="text-[22px] font-semibold uppercase tracking-[1.5px] mb-2 mt-1" style={{ fontFamily: "var(--font-display)" }}>
              What is a COA?
            </h2>
            <p className="text-[15px] text-[var(--prg-text-secondary)] leading-[1.75] mb-3">
              A Certificate of Analysis (COA) is a laboratory-issued document verifying the identity,
              purity, and composition of a chemical substance. Our COAs are generated by independent
              third-party analytical laboratories using validated methods.
            </p>
            <p className="text-[13px] text-[var(--prg-text-muted)]">
              COAs typically include HPLC purity analysis, mass spectrometry confirmation, and
              additional quality metrics specific to each compound.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-5 mb-12">
            {[
              { icon: Beaker, title: "HPLC Analysis", desc: "High-Performance Liquid Chromatography verifies chemical purity to 99%+ threshold." },
              { icon: FileCheck, title: "Mass Spectrometry", desc: "MS confirmation ensures molecular identity matches the expected compound." },
              { icon: ShieldCheck, title: "Independent Labs", desc: "Testing performed by accredited third-party laboratories, not in-house." },
            ].map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.title} className="bg-white border border-[var(--prg-border)] rounded-[var(--prg-radius-lg)] p-6">
                  <div className="w-12 h-12 rounded-[var(--prg-radius)] bg-[rgba(30,58,95,0.06)] flex items-center justify-center text-[var(--prg-accent)] mb-4">
                    <Icon size={22} />
                  </div>
                  <h3 className="text-[14px] font-semibold uppercase tracking-[1px] mb-2" style={{ fontFamily: "var(--font-display)" }}>
                    {item.title}
                  </h3>
                  <p className="text-xs text-[var(--prg-text-secondary)] leading-[1.7]">{item.desc}</p>
                </div>
              );
            })}
          </div>

          <h2 className="text-[22px] font-semibold uppercase tracking-[1.5px] mb-5" style={{ fontFamily: "var(--font-display)" }}>
            Available COAs
          </h2>

          {products.length === 0 ? (
            <div className="bg-white border border-[var(--prg-border)] rounded-[var(--prg-radius-lg)] p-8 text-center">
              <FileCheck size={40} className="mx-auto mb-3 text-[var(--prg-text-muted)] opacity-40" />
              <p className="text-sm text-[var(--prg-text-muted)]">
                COA documents are added on a rolling basis. If you need a COA for a specific product,
                please <Link href="/contact" className="text-[var(--prg-accent)] underline">contact us</Link>.
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
              {products.map((p) => (
                <div key={p.id} className="bg-white border border-[var(--prg-border)] rounded-[var(--prg-radius-lg)] p-6 prg-card-hover">
                  <h3 className="text-[15px] font-semibold mb-2">{p.displayName}</h3>
                  <p className="text-[13px] text-[var(--prg-text-muted)] mb-3">{p.categoryLabel}</p>
                  <p className="text-xs font-mono text-[var(--prg-text-muted)] mb-4">{p.sku}</p>
                  <a
                    href={p.coaUrl ?? "#"}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 text-[13px] text-[var(--prg-accent)] font-medium hover:underline"
                  >
                    <Download size={14} /> View COA
                  </a>
                </div>
              ))}
            </div>
          )}
        </div>
      </section>
    </>
  );
}
